--liquibase formatted sql

-- changeset auth-service:1.1
CREATE TABLE IF NOT EXISTS credential
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 1 NOT NULL,
    created_dttm TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    CONSTRAINT credential_version_check
    CHECK (version >= 1)
    );

-- changeset auth-service:1.2
COMMENT ON COLUMN credential.id IS 'Identifier';
COMMENT ON COLUMN credential.version IS 'Optimistic locking version. large range number from -9223372036854775808 to +9223372036854775807';
COMMENT ON COLUMN credential.created_dttm IS 'Creation timestamp. Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';
COMMENT ON COLUMN credential.updated_at IS 'Last update timestamp. Format ISO 8601: YYYY-MM-DD hh:mm:ss.000000';
COMMENT ON COLUMN credential.email IS 'User email address. Must be unique.';
COMMENT ON COLUMN credential.password IS 'Hashed password.';
COMMENT ON COLUMN credential.role IS 'User role (e.g., ADMIN, USER).';

-- changeset auth-service:1.3
CREATE UNIQUE INDEX idx_credential_email ON credential (email);