--liquibase formatted sql

-- changeset auth-service:2.1
CREATE TABLE IF NOT EXISTS refresh_token
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT DEFAULT 1 NOT NULL,
    created_dttm TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    token VARCHAR(512) NOT NULL UNIQUE,
    expiry_date TIMESTAMP(6) NOT NULL,
    credential_id BIGINT NOT NULL,
    CONSTRAINT refresh_token_version_check
    CHECK (version >= 1),
    CONSTRAINT fk_refresh_token_credential
    FOREIGN KEY (credential_id)
    REFERENCES credential (id)
    ON DELETE CASCADE
    );

-- changeset auth-service:2.2
COMMENT ON COLUMN refresh_token.id IS 'Identifier';
COMMENT ON COLUMN refresh_token.version IS 'Optimistic locking version.';
COMMENT ON COLUMN refresh_token.created_dttm IS 'Creation timestamp.';
COMMENT ON COLUMN refresh_token.updated_at IS 'Last update timestamp.';
COMMENT ON COLUMN refresh_token.token IS 'Unique refresh token string.';
COMMENT ON COLUMN refresh_token.expiry_date IS 'Token expiration date/time (Instant mapping).';
COMMENT ON COLUMN refresh_token.credential_id IS 'Foreign key to the associated credential (user).';

-- changeset auth-service:2.3
CREATE INDEX idx_refresh_token_credential_id ON refresh_token (credential_id);