spring:
  data:
    redis:
      host: ${USER_SERVICE_REDIS_HOST:localhost}
      port: ${USER_SERVICE_REDIS_PORT:6379}
      password: ${USER_SERVICE_REDIS_PASSWORD}
      timeout: 6000ms

  liquibase:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none

  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${USER_SERVICE_POSTGRES_HOST}:${USER_SERVICE_POSTGRES_PORT}/${USER_SERVICE_POSTGRES_DB}
    username: ${USER_SERVICE_POSTGRES_USER}
    password: ${USER_SERVICE_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: 8000


springdoc:
  swagger-ui:
    url: /v3/api-docs
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs