spring:
  data:
    redis:
      host: ${USER_SERVICE_REDIS_HOST}
      port: ${USER_SERVICE_REDIS_PORT}
      password: ${USER_SERVICE_REDIS_PASSWORD}
      timeout: 6000ms

  liquibase:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://${USER_SERVICE_POSTGRES_HOST}:${USER_SERVICE_POSTGRES_PORT}/${USER_SERVICE_POSTGRES_DB}
    username: ${USER_SERVICE_POSTGRES_USER}
    password: ${USER_SERVICE_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver