create table IF NOT EXISTS users
(
    id bigint generated by default as identity primary key,
    created_dttm timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at timestamp(6) default CURRENT_TIMESTAMP not null,
    version bigint default 1 not null
    constraint users_version_check
    check (version > 0)
    constraint users_version_check1
    check (version >= 1),
    birth_date timestamp(6) not null,
    email varchar(50) not null,
    name varchar(50) not null,
    surname varchar(50) not null
    );

create index idx_app_user_email on users (email);