create table IF NOT EXISTS card_info
(
    id bigint generated by default as identity primary key,
    created_dttm timestamp(6) default CURRENT_TIMESTAMP not null,
    updated_at timestamp(6) default CURRENT_TIMESTAMP not null,
    version bigint default 1 not null
    constraint card_info_version_check
    check (version > 0)
    constraint card_info_version_check1
    check (version >= 1),
    expiration_date timestamp(6) not null,
    holder varchar(255) not null,
    number varchar(16) not null,
    user_id bigint not null
    constraint fk_card_user
    references users
    );

create index idx_card_info_user_id on card_info (user_id);
create index idx_card_info_number on card_info (number);