version: '3.8'

services:

  user-service-db:
    image: postgres:16
    container_name: user-service-db
    env_file:
      - docker.env
    environment:
      - POSTGRES_USER=${USER_SERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${USER_SERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${USER_SERVICE_POSTGRES_DB}
    ports:
      - "5400:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: user-service-redis
    env_file:
      - docker.env
    environment:
      - REDIS_PASSWORD=${USER_SERVICE_REDIS_PASSWORD}
    command: [
      "redis-server",
      "--appendonly", "yes",
      "--requirepass", "${USER_SERVICE_REDIS_PASSWORD}"
    ]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8000:8000"
    env_file:
      - docker.env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - user-service-db
      - redis

volumes:
  pgdata:
  redisdata: